name: portfolio
description: My portfolio site.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.2+5

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_route: ^7.8.4
  bloc_concurrency: ^0.2.3
  colorize: ^3.0.0
  dio: ^5.4.0
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  get_it: ^7.6.7
  intl: ^0.18.1
  logging: ^1.2.0
  ndialog: ^4.3.1
  url_launcher: ^6.2.4
  url_strategy: ^0.2.0

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner:
  dart_code_metrics_presets: ^2.8.0
  flutter_lints: ^3.0.1
  husky: ^0.1.7
  intl_utils: ^2.8.7

#dependency_overrides:
#  intl: ^0.18.0

flutter:
  uses-material-design: true

  assets:
    - assets/png/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 800
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated

flutter_icons:
  android: false
  ios: false
  web:
    generate: true
    image_path: "assets/png/I3.png"