name: portfolio
description: My portfolio site.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+2

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  bloc_concurrency: ^0.2.1
  colorize: ^3.0.0
  cupertino_icons: ^1.0.5
  dio: ^5.0.3
  flutter_bloc: ^8.1.2
  flutter_launcher_icons: ^0.12.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  go_router: ^6.4.0
  intl: ^0.18.0
  json_annotation: ^4.8.0
  logging: ^1.1.1
  ndialog: ^4.3.0
  url_launcher: ^6.1.10
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  dart_code_metrics: ^5.6.0
  flutter_lints: ^2.0.1
  freezed: ^2.3.2
  intl_utils: ^2.8.2
  json_serializable: ^6.6.1

dependency_overrides:
  intl: ^0.18.0

flutter:
  uses-material-design: true

  assets:
    - assets/png/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 800
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated

flutter_icons:
  android: false
  ios: false
  web:
    generate: true
    image_path: "assets/png/I3.png"